### PR TITLE
Added command-line arguments to Python localtest.

### PR DESCRIPTION
**Pull request by griffinbholt**
Let me know what you think. - Griffin

### CODE REVIEW

**Comment by dylan-asmar** [comment]
Thanks!

**Comment by dylan-asmar** [comment]
I'm thinking we should make similar changes to project 1 as well. 
I'll create an issue to track as a "to-do"

**Comment by griffinbholt** [comment]
Good idea. Do you want me to do that?

**Comment by dylan-asmar** [comment]
If you have time, please do. Otherwise, we need to make sure it gets accomplished before the course is offered again.

**Comment by griffinbholt** [comment]
Done!

Thanks,
Griffin Holt

**Pull request merged**
